project:
  type: website
  output-dir: docs

website:
  # title: "HOME"
  back-to-top-navigation: true

  # sidebar:
  #   contents:
  #     - href: openings/index.qmd
  #       text: "<span class='sign-board rboarder'>Open<span class='flicker sign-board'>ings</span></span>"

  navbar:
    left:
      - text: HOME
        href: home.html

      - text: Research
        href: research/index.qmd

      - href: publications/index.qmd
        text: Publications

      - href: blogs/index.qmd
        text: Blogs

      - text: Resources
        menu:
        - text: Softwares
          href: resources/softwares.qmd

      - href: team/index.qmd
        text: Team

      - href: contactus.qmd
        text: Contact Us

      - href: openings/index.qmd
        text: "<span class='sign-board rboarder'>Open<span class='flicker sign-board'>ings</span></span>"

    right:
      - icon: "google scholar"
        href: https://scholar.google.com/citations?user=lPTdGRMAAAAJ&hl=en
      - icon: linkedin
        href: https://www.linkedin.com/in/ravinderbhattoo
      - icon: github
        href: https://github.com/ravinderbhattoo/
      - icon: orcid
        text: <img width=20 src=https://orcid.org/assets/vectors/orcid.logo.icon.svg title=ORCID />
        href: https://orcid.org/0000-0003-0323-9108
      - icon: "research gate"
        text: "<img width=20 src=https://help.researchgate.net/hc/theming_assets/01HZPWT1CS5WRP04ZJX0DM6135 title='Research Gate' />"
        href: https://www.researchgate.net/profile/Ravinder_Bhattoo?ev=hdr_xprf

  # announcement:
  #   content: "**New** - this is an announcement"
  #   position: below-navbar

  page-footer:
    center:
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd

format:
  html:
    theme: cosmo
    css: [
          "styles/styles.css",
          "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css",
          "http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900",
          ]
    toc: true



